### ISSUE TITLE
awesome-mechanical-keyboard

### ISSUE THREAD

**Issue by 532910** [help-14/mechanical-keyboard#21]
What is the difference with https://github.com/BenRoe/awesome-mechanical-keyboard?
What is the reason for a separate project?
Should both be merged?

**Comment by dbrw** [comment]
This project says on it's readme:
> This list will help you quickly find your favorite layout and you can start DIY your own custom keyboard.

And the other project says:
> The goal of this repository is to collect mechanical keyboard related projects (preferably Open Source).

I think that's different enough, also it is okay to have too many project for this kind of things.

But who am I to judge?

**Comment by 532910** [comment]
it's okay to have many keyboard projects, but the index should be one

**Comment by help-14** [comment]
My project was created way before the other project.
Also I don't really like the way they are using to create the website, so I think I'll do it my way.
Nothing is too much index :))))
