### ISSUE TITLE
Pheromone Keyboard isn’t Open Source

### ISSUE THREAD

**Issue by FlorianWendelborn** [help-14/mechanical-keyboard#26]
See <https://github.com/luantty2/pheromone_keyboard#copyright>. The project *explicitly* states that it does not have any license (be it an open-source one or not)

**Comment by help-14** [comment]
Interesting, I'm honestly don't know what to do in this case, maybe just remove the link on the list or change "open source list" to "DIY list".

**Comment by FlorianWendelborn** [comment]
@help-14 I’d recommend just adding a small icon that indicates the license to the links. A lot of similar projects do it like this.

See <https://github.com/jaywcjlove/awesome-mac>, <https://github.com/iCHAIT/awesome-macOS>, and <https://github.com/serhii-londar/open-source-mac-os-apps>

**Comment by help-14** [comment]
Finally it's done :)))

**Comment by FlorianWendelborn** [comment]
@help-14 perfect, good job
