### ISSUE TITLE
Split ergonomic keyboards that are not included currently

### ISSUE THREAD

**Issue by Ross-Li** [help-14/mechanical-keyboard#50]
A few split ergonomic keyboards that are not included currently:

1. Cantor: 
Cantor keyboard, a 42 key diodeless split keyboard.
https://github.com/diepala/cantor

2. Piantor:
The Piantor Keyboard is a beginner-friendly, easy-to-solder, 42-key or 36-key, diodeless, low profile aggressive column staggered, hotswappable and non-hotswappable, programmable ergonomic mechanical split keyboard powered by Raspberry Pi Pico or other compatible RP2040 boards. It is based on the Cantor Keyboard.
https://github.com/beekeeb/piantor

3. Sweep: 
Sweep - a small promicro based keyboard inspired by the Ferris.
https://github.com/davidphilipbarr/Sweep

4. Ferris:
A low profile split keyboard designed to satisfy one single use case elegantly
https://github.com/pierrechevalier83/ferris

5. Microdox
Microdox Keyboard Build Guides
https://github.com/waffle87/microdox

I think there are other repos that specifically collect split ergonomic keyboards, but it would also be great if you could add these here.

**Comment by help-14** [comment]
Added!
